export {default as LandingPage} from './LandingPage/LandingPage'
export {default as PageNotFound} from './PageNotFound/PageNotfound'
export {default as SignupPage} from './SignupPage/SignupPage'
export {default as LoginPage} from './LoginPage/LoginPage'
export {default as Dashboard} from './Dashboard/Dashboard'
export {default as FavMoviesPage} from './FavMoviesPage/FavMoviesPage'